import json
import os
# Example using the google-genai or openai SDK
# Make sure to install it first: pip install google-genai
from google import genai 

def load_pipeline(filepath):
    with open(filepath, 'r') as file:
        return json.load(file)

def run_ai_travel_planner():
    # 1. Load the JSON configuration
    config = load_pipeline('pipeline.json')
    stages = config['pipeline_stages']
    
    print(f"Starting Project: {config['project']}")
    print(f"Topic: {config['selected_topic']}\n" + "="*40)
    
    # 2. Extract components from your JSON
    system_instruction = stages['step_1']['prompt_design']
    few_shot_examples = stages['step_2']['examples']
    cot_instruction = stages['step_4']['prompt_design']
    
    # 3. Initialize the AI Client
    # Ensure your API key is set in your terminal environment: export GEMINI_API_KEY="your-key"
    client = genai.Client()
    
    # 4. Define your actual user input trip query
    user_query = "I want a 3-day budget trip to Paris focusing on art and museums."
    
    # 5. Construct the full prompt leveraging your pipeline configuration
    full_prompt = f"""
    {system_instruction}
    
    Here are some examples of how to format your response:
    {json.dumps(few_shot_examples, indent=2)}
    
    When processing the request, follow these explicit reasoning steps:
    {cot_instruction}
    
    User Request: {user_query}
    """
    
    print("Sending prompt pipeline to AI...")
    
    # 6. Generate the content
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=full_prompt,
    )
    
    # Print the output generated by running the pipeline
    print("\n" + "="*10 + " AI OUTPUT " + "="*10)
    print(response.text)

if __name__ == "__main__":
    run_ai_travel_planner()
